#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-puppetdb', '6.0.2'
mod 'puppetlabs-inifile', '2.1.1'
mod 'puppetlabs-stdlib', '4.24.0'
mod 'puppetlabs-concat', '4.1.1'
mod 'puppetlabs-firewall', '1.11.0'
mod 'puppetlabs-ntp', '7.0.0'
mod 'puppetlabs-apt', '4.4.1'
mod 'puppetlabs-postgresql', '5.2.1'
